### ISSUE TITLE
Weird response when adding time_card entry

### ISSUE THREAD

**Issue by duckinator** [rubytogether/rubytogether-lita#5]
When adding a time card entry, it returns a response that contains no actual information, and seems to try (but fail) to have a code snippet.

![screenshot_2017-04-18_18-38-05](https://cloud.githubusercontent.com/assets/39698/25156193/1e665520-2467-11e7-89f5-5fda1b0e67ec.png)

**Comment by segiddins** [comment]
Known issue, never bothered to fix it. (It's because following redirects was hard)

**Comment by duckinator** [comment]
Figured it was known, but still seems good to have an actual issue for it so someone else can potentially attempt working on it. 😃
