### ISSUE TITLE
Way to view time card(s)?

### ISSUE THREAD

**Issue by duckinator** [rubytogether/rubytogether-lita#6]
It'd be neat to have a way to view my time card.

Maybe have just `time_card` do this?

**Comment by segiddins** [comment]
`@lita time_card monthly`

**Comment by duckinator** [comment]
Good to know! Would be neat to have a less-noisy option that only shows my time card eventually, but `time_card monthly` definitely works, so no rush.

(Also, it looks like the thing where it doesn't actually use code formatting is an issue in multiple places?)

**Comment by segiddins** [comment]
It's an issue with slack seeming only respecting triple bacticks for content under a certain size

**Comment by indirect** [comment]
partially fixed by making lita use separate triple backticks for each individual person. ultimately, I think the response will need to be a snippet or a post, via a different api.
